<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\modules\auctions\Relora.Auctions.Domain\Relora.Auctions.Domain.csproj" />
    <ProjectReference Include="..\..\modules\items\Relora.Items.Application\Relora.Items.Application.csproj" />
    <ProjectReference Include="..\..\modules\items\Relora.Items.Domain\Relora.Items.Domain.csproj" />
    <ProjectReference Include="..\..\modules\orders\Relora.Orders.Application\Relora.Orders.Application.csproj" />
    <ProjectReference Include="..\..\modules\orders\Relora.Orders.Domain\Relora.Orders.Domain.csproj" />
    <ProjectReference Include="..\..\Relora.Payments.Domain\Relora.Payments.Domain.csproj" />
  </ItemGroup>
</Project>
