<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Relora.Support.Application\Relora.Support.Application.csproj" />
    <ProjectReference Include="..\Relora.Support.Domain\Relora.Support.Domain.csproj" />
    <ProjectReference Include="..\..\..\persistance\Relora.Persistance\Relora.Persistance.csproj" />
  </ItemGroup>
</Project>
