<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.12" />
	<PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\persistance\Relora.Persistance\Relora.Persistance.csproj" />
    <ProjectReference Include="..\..\..\shared\Relora.Shared.Domain\Relora.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\auctions\Relora.Auctions.Application\Relora.Auctions.Application.csproj" />
    <ProjectReference Include="..\..\auctions\Relora.Auctions.Domain\Relora.Auctions.Domain.csproj" />
    <ProjectReference Include="..\Relora.Bids.Domain\Relora.Bids.Domain.csproj" />
  </ItemGroup>
</Project>
